name: "Mount Lambda Layer"
description: "Mount lambda layer dependencies as repository dependecies"
inputs:
  arn:
    description: "ARN of the layer version"
    required: true
runs:
  using: node16
  main: dist/index.js
branding:
  icon: layers
  color: orange
